tests: expect intermittent warning on azure pro images. avoid client.destroy
Avoid client.destroy within the cloud_session.launch context manager
as it already performs cloud.destroy on context exit which calls
instance.destroy. This avoids the following error seen by pycloudlib
on Azure instances:

  <pycloudlib.azure.instance.AzureInstance object at ....

  @property
  def id(self):
      """Return instance id."""
      return self._instance["vm"].id
               ^^^^^^^^^^^^^^^^^^^^
      TypeError: 'NoneType' object is not subscriptable